---

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install mopidy external extensions.
  pip:
    name: "{{ item }}"
    state: present
  with_items: mopidy_external_extensions
  notify: restart mopidy

- include: settings.yml
  vars:
    settings: "{{ mopidy_settings }}"

- name: Ensure Mopidy is started on boot.
  service:
    name: mopidy
    state: started
    enabled: yes
